### ISSUE TITLE
Support a --version or similar to help automation and version checking

### ISSUE THREAD

**Issue by sbailliez** [mbryzek/schema-evolution-manager#23]
Not critical but would be nice to have --version being supported by the commands so that it helps scripting / version checking.

Right now I'm doing: 

  readlink /usr/local/lib/schema-evolution-manager | awk -F- '{print $4}'

which does the deal.

**Comment by mbryzek** [comment]
Right now you can do:

$ sem-info version
0.9.20

This was added in 0.9.16 - does this do what you need?

**Comment by mbryzek** [comment]
closing - older question that is supported. Pls re-open if you were thinking about a different solution
