### ISSUE TITLE
Support custom ports

### ISSUE THREAD

**Issue by Seanstoppable** [mbryzek/schema-evolution-manager#24]
I'm running a postgres docker container, and as not to interfere with my existing postgres setup, I am exposing it on a non-standard port. Should be able to specify an optional port to sem-apply in order to support this, and other non-standard setups.

**Comment by Seanstoppable** [comment]
Actually unnecessary, since you can use the PGPORT variable, and the PSQL client will automatically try to use that port.

**Comment by mbryzek** [comment]
I do like having it as a command line option (surprising that we didn't have from beginning) - let's keep open as I want to add this feature

**Comment by Seanstoppable** [comment]
Closed via #29
