### ISSUE TITLE
Create a sem-baseline command

### ISSUE THREAD

**Issue by Seanstoppable** [mbryzek/schema-evolution-manager#27]
Ran into this at my current company, where someone went to prod without sem and now needs to switch. 

Need the ability to apply the bootstrap scripts and add an initial migration file to the migration table without actually applying it (since it has already been applied).

Baseline is terminology taken from other schema migration tools.

**Comment by mbryzek** [comment]
Sean added in https://github.com/mbryzek/schema-evolution-manager/pull/28
