### ISSUE TITLE
Invalid command line on windows systems

### ISSUE THREAD

**Issue by chris-lu** [mbryzek/schema-evolution-manager#44]
Executing the Db scripts from Windows leads to "Invalid Command Line" due to stderr redirect notation that is not compatible. ( &> )
I'd suggest to to update the line 77 of db.rb with:

```
 result = `#{command} > #{output} 2>&1`.strip
```

instead of
```
 result = `#{command} &> #{output}`.strip
```

**Comment by mbryzek** [comment]
Thanks - 0.9.32 is out w/ your suggested change

**Comment by chris-lu** [comment]
By the way, many thanks for your quick reply and your great project !

**Comment by mbryzek** [comment]
thanks for the great bug report! much appreciated
