### ISSUE TITLE
Extra semicolon in latest version

### ISSUE THREAD

**Issue by muttonhead** [mbryzek/schema-evolution-manager#73]
Hi - 
This commit that created a new version just now seems to have an extra semicolon here
```
new.updated_at = now();;
```

This is giving a syntax error at least on PostgreSQL 13 that we are using
```
ERROR:  syntax error at or near ";"
LINE 6:     new.updated_at = now();;
                                   ^
```
Thanks

**Comment by mbryzek** [comment]
@muttonhead Thank you - Fixed in https://github.com/mbryzek/schema-evolution-manager/pull/74 (releasing now)
